### ISSUE TITLE
Help regarding learning path

### ISSUE THREAD

**Issue by parulagg27** [facebook-developer-circle-delhi/Ask-The-Community#1]
**A community member asks anonymously:** 

"Hey! 
I have basic knowledge of C++ and Python and also of OOPS concepts. But I'm not good at data structures and algos, and really interested in development (web and blockchain). I don't have any programing background and I'm completely self taught programmer. My friends are already achieving  heights in this field via development  and I don't  want to again get struck  with the basics. Whenever I think of starting with development, I get struck  in this  infinite  loop of deciding phase because  of fear of taking any wrong step. People say we need to be really good at data structures before starting with development  but I'm unable to figure out how those deadly topics are helping in development. Can these two things of doing basics and development be done parallely?
 How should I proceed further and overcome this? I want to stand out competition and have a good interest in programming as well. But as I'm a slow learner,  people goes so far away in that time and manage to do so many  things, and finding myself struck in this infinite loop of deciding and doing basics frustrates me further. Any help regarding this on how  to overcome this loop, what  should be my learning path, and how should I proceed, would be highly appreciated."

**Comment by saranshkataria** [comment]
In my opinion, The best way to learn things is by doing. I am not that great at data structures and algorithms either. And once you enter the industry, you rarely use them. So don't worry about that or about being a slow learner. Everyone learns at their own pace and you are competing with yourself in the end.

Also, instead of focusing on the syntax of languages, focus on concepts and try and understand why a particular technique was used, why not something else. Programming is one field wherein you need to understand why something does not work as well as why it does work. Grasping those details are super important.

I share the frustration of other developers moving ahead at a radically faster pace than I can, but I also understand that everyone has a different exposure to things. Some people focus on a single stack and hence get deep into it and are able to understand things in that stack at ease but they will not be able to answer anything else outside their domain. And I am not the one stack guy, so I am okay with that. What matters is building side projects (I struggle at that too), and to just keep learning.

For suggestions regarding learning path: I prefer experimenting with areas (mobile/web/chatbots/AI/ML/AR/VR) and figure out which one I like. Then accordingly, after choosing one, I see which all options/platforms/frameworks are available and see a comparison of them. After some research, choose one, build something small with it and see if you like it. If you do, explore more of it, else start with something else. And then keep on learning and unlearning things as needed.

**Comment by apoorvtomar2222** [comment]
And to add. 

What my personal experience was that , at the starting it is always difficult, but as you start learning more, it becomes easy.

And its absolutely correct , once you are through with the basic, you yourself will start exploring the deeper concepts.

For reference. Even  I started exploring different library now about How they did something. So that I can implement that in my solution.

So keep exploring new concept. You will make it to the other side of the journey.

**Comment by jatin69** [comment]
And to add.

There's only one way to compete with someone who's smarter and faster.

> Put more time and effort.

**Comment by IamManchanda** [comment]
First and Foremost ... Working in a real project instead of toy project helps a lot in improving yourself in Data Structures and Algorithms ... Learning data structures is not a thing that can come in one day ... It needs some project where you can implement the learning and have a taste of it by your own.

Apart from that 
One thing I can surely say knowing those built in functions/methods of the language and creating your own using them helps a lot lot thinking about the problem in hand for the given logic. Reading the Docs (**RTFM**) is gold to me...

If you are looking for some practise practise, I would suggest
JavaScript: https://www.udemy.com/coding-interview-bootcamp-algorithms-and-data-structure/
Python: https://www.udemy.com/python-for-data-structures-algorithms-and-interviews/

**Comment by IamManchanda** [comment]
Also If you are learning JavaScript ... Knowing those built-in functions can be a bit daunting as a beginner I am supposing ...
What would I would recommend is fetch this link => https://www.google.co.in/search?q=prototype+mdn
Also apart from that ... using utility library like [lodash](https://lodash.com/docs/4.17.10) or [Ramda](https://ramdajs.com/docs/) would be a very very good option 

I repeat not about learning them ... It's all about going through them and add in your memory that you can come back later when you have a problem in hand that can be solved by these :)

**Comment by vaibhavsingh97** [comment]
I was once in the situation there and what I was lacking is that I was not giving a start, instead, I was searching for tutorials, reading blogs and seeing everybody succeeding in their goal. I also want to be there, but don't know what to do so I just subscribed to one course, it was free as I found it on. internet, and tried to learn and I learned quickly, in your case don't give up if you are a slow learner. just learned it completely what you are learning. As suggested by @saranshkataria just explore fields, there are many videos on the internet and courses on the internet which doesn't have prerequisites, so anybody can learn, just subscribe it and try to learn it all and soon you will find your interest.
