### ISSUE TITLE
Skills and approach required for research work in bioinformatics

### ISSUE THREAD

**Issue by parulagg27** [facebook-developer-circle-delhi/Ask-The-Community#24]
**A community member asks anonymously:**

" I learnt some industrial experience by doing an internship. I wish to go for research work in bioinformatics and wish to get a job in same but I have no ideas what all skills should I learn, whom to approach. "

**Comment by prithaupadhyay** [comment]
Bioinformatics is a broad field where we aim to extract some knowledge from biological data. Now, the research work will depend upon your areas of interest. There can be computational research in bioinformatics using Image Processing, Computer Vision, Deep Learning and in many such areas. As of now, you can begin with reading about some existing research papers. That will give you an idea about what you are going to do and then you can follow any of the fields. My current research involves Image Processing and Computer Vision.
Feel free to ask questions.

**Comment by evoxtorm** [comment]
Yeah very good question. I was also finding this answer during 3rd year of Engineering in Biotechnology while I'm also one of the guy who wants to further want to research in this field. To find this answer I've started to work under a scientist in government research institute but I find out they are lagging behind the technology and there work is not like a developer thing they just use tools to do all the things. I got disappointed by this . Then when I was in final year of my engineering I was able to clear GSOC for Open Bioinformatic Foundation. I saw and worked with some of the best open source guys who are working on bioinformatics. 
So I learn some of the things which will clear your doubts:
1. Skills are in terms of both biology and development. You have good knowledge of biology so you can approach a real world bioinformatic problem. In development you should know a scripting language majorly used are python or perl . Sometimes R also . Now if you have some skills in data science then it is good. Most of the research organization now use DSL(Domain specific language) like nextflow or cwl(common workflow language).
2. At least you have Master degree for a job in Bioinformatic or computational biology.
3. Have some good Internship experiences so that you will be not a burden for your organization.
4. Some good contacts because most of the good research organization asks for referee or mentors so indeed it is important.
5. To want to go for research get the masters done and apply for research assistant ship with PhD because it is very hard to find a good bioinformatics job with bachelor's or master degree.
6. Skills can also be dependent on what type of research you want to do. Like drug Discovery or cancer based research or on next generation sequencing.

PS: All the best for it btw I've applied for endless bioinformatics job but they didn't consider you, if you just having bachelor's degree. So it's better to do Masters and then do  research work of your field of interest with PhD.

**Comment by parulagg27** [comment]
Thank you for your answers @prithaupadhyay @evoxtorm :)
Closing this issue now!
