### ISSUE TITLE
Research work on biology related topics with CS

### ISSUE THREAD

**Issue by parulagg27** [facebook-developer-circle-delhi/Ask-The-Community#26]
**A community member asks anonymously:**

" I am an undergraduate computer science student and I wish to research on some biology related topics with computer science. Though they are many tools, method, resources available online, I am not able to find something concrete that guides me to what kind of work I wish to do. Can anyone guide me about the same.
Be it suggestions regarding the kind of approach I should take i.e, languages or data-science track projects or anything.
Thank you"

**Comment by harshitjuneja** [comment]
The information that you have provided doesn't help much. Maybe what your research objectives are would help. If you aren't very clear with that, I suggest reading reputed journals and trying to reach at the specified result.

As an undergrad student, I suggest you work out with one your professors whose research you might be interested in. A more detailed topic around your research interest might have led to a better answer though.

 All the best!

**Comment by evoxtorm** [comment]
Hey There,
I'm a biotech engineering student so I'm eligible for answering this question. In the second year of my engineering, I feel the same what topic should I choose and how I should proceed further. 
As you've not given much information so I will assume most of the things. I will explain this in a few points.
0. Learn any scripting language like python Perl etc. It will help you in most of the major projects.
1. You should study something about bioinformatics or computational biology as both of there names tells everything. Most Biology + software things lie in this domain.
2. Find your true objective because biology is vast and you've tons of things which you can work on. So first clear that it will be core biology project or it just uses other biological library and making pipeline and other stuff.
3. One of the important things which part of biology you want to want like cancer is a hot topic nowadays. One of the important topics is drug discovery software or their visualization. Apart from this Bioinformatics pipelines are nowadays a major topic among bioinformatician and computational biologist using domain specific language.

PS:- I also go through the same phase so give time to yourself and find your strengths. All the best

**Comment by parulagg27** [comment]
Thanks for your answers @harshitjuneja @evoxtorm!
Closing this issue now.
