### ISSUE TITLE
Help regarding interview preparation

### ISSUE THREAD

**Issue by parulagg27** [facebook-developer-circle-delhi/Ask-The-Community#4]
A community member asked anonymously:

"Hello! 
So, I got shortlisted for Software Development Intern role in a big well known company and have my video conferencing Technical interview round next week. But I have no clue how I'll be able to crack it. It's been a long time I've not been in touch of DS and Algos as I got shifted more towards development side. I remember, I last studied them for my college exams. Is it possible to prepare them well in this small duration of 1 week. What should be the smart strategy to prepare them well, sufficient enough to crack the interviews. Which all topics I should focus upon more, and which sites would be good to follow to help me prepare on time. Also, should I focus only on concepts, the algorithm and it's implementation and space time analysis, or should I practice questions from sites such as hackerrank, hackerearth, etc ( I know it'll be more time taking, but Iiterally I have low confidence in DS and algo right now not being in touch of them for long time.) I'm not sure, whether I'll be able to crack the interview( by heart, I literally want it), but still I want to give my 100% in it's interview preparation( despite of having low confidence with concepts right now), because such opportunities never comes easily. Thanks. "

**Comment by saranshkataria** [comment]
The answer to this will vary according to the organization you are applying for. Instead of reading everything, check online what all do they usually ask in their interviews and plan accordingly. Geeks for geeks gives a good idea about the major organizations and you can get some questions from there too. Get the basics right instead of trying to refresh everything since if your concepts would be clear, you can answer questions that build upon those.

Good luck! 👍

**Comment by parulagg27** [comment]
Great. Closing this issue now!
