### ISSUE TITLE
Help with Async Actions

### ISSUE THREAD

**Issue by gaurav-gogia** [facebook-developer-circle-delhi/Ask-The-Community#6]
Hi all!

I have an async action and I wish to handle loading. 

The async action is a simple post API call. I wish to start loading when the call is started and end loading when the call ends. [Here is my code](https://gist.github.com/DesmondANIMUS/854f2e896a78f6396433fc4b1b2db727). I am able to dispatch the event and take care of API part but I'm not able to fix this loading issue. Someone told me to add the loading state to the store itself but I still can't figure it out. Please advise. 

Thanks!

**Comment by manishekaneja** [comment]
I am assuming that you are able to handle the API call and your actual problem is related to loading status only.

Well, I would have preferred to go for a callback function instead of using async/await. So that, I can change the state of the loader again using that callback function in the API call.
  
But Since you are using async/await, Have you tried calling the "toggleLoading()" again after the "createLink()" call?

**Comment by harshitjuneja** [comment]
@DesmondANIMUS Make a post to the facebook group. Let's help you out there. Make sure you close this issue.

**Comment by gaurav-gogia** [comment]
Sure
